[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.22"
  CGO_ENABLED = "0"

[functions]
  node_bundler = "esbuild"
  included_files = ["bin/**"]

[[redirects]]
  from = "/slack/oye"
  to = "/.netlify/functions/slack-oye"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/debug"
  to = "/.netlify/functions/debug"
  status = 200
  force = true
