[build]
  command = "./deploy.sh"
  publish = "."

[build.environment]
  GO_VERSION = "1.22"

[functions]
  directory = "functions"

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/slack/*"
  to = "/.netlify/functions/slack-command"
  status = 200
