[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.22"
  CGO_ENABLED = "0"

[functions]
  node_bundler = "esbuild"
  included_files = ["bin/**"]

# Support for Go server function (alternative deployment)
[functions.go-server]
  directory = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/slack/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Alternative: Go server redirects (comment above and uncomment these for Go server approach)
# [[redirects]]
#   from = "/*"
#   to = "/.netlify/functions/go-server/:splat"
#   status = 200
#   force = true
