[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  GO_VERSION = "1.22"
  CGO_ENABLED = "0"

[functions]
  node_bundler = "esbuild"
  included_files = ["bin/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/slack/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
